package edu.ucne.recrearte.presentation.signUp

data class SignUpUiState(
    val currentStep: Int = 1,
    val email: String = "",
    val password: String = "",
    val firstName: String = "",
    val lastName: String = "",
    val userName: String = "",
    val phoneNumber: String = "",
    val documentNumber: String = "",
    val isArtist: Boolean = false,
    val address: String = "",
    val artStyle: String = "",
    val socialMediaLinks: String = "",
    val isLoading: Boolean = false,
    val isSuccess: Boolean = false,
    val errorEmail: String? = null,
    val errorPassword: String? = null,
    val errorFirstName: String? = null,
    val errorLastName: String? = null,
    val errorUserName: String? = null,
    val errorPhoneNumber: String? = null,
    val errorDocumentNumber: String? = null,
    val errorAddress: String? = null,
    val errorArtStyle: String? = null,
    val errorSocialMediaLinks: String? = null,
    val errorMessage: String? = null,
)